# Automation Team - ******* Belo
# Agosto de 2019
# v1.2

version: '2'
services:
  # All in One appication
  AIO:
   # image: docker.corp.*******.org/automation-bel/aio:latest
    image: testeteste:latest
    volumes:
      - /run/dbus:/host/run/dbus
      - /storage/pi/:/storage/pi/
    ports:
      - 8082:5900
    privileged: true
    tty: false
    hostname: *******RASP370
    dns_search: corp.*******.org
